plugins {
    id "com.android.library"
}

android {
    namespace "com.qairt.npudiagnostics"
    compileSdk 35
    defaultConfig {
        minSdk 26
        targetSdk 35
        ndk { abiFilters "arm64-v8a" }
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -fexceptions -frtti"
                arguments "-DQAIRT_ROOT=E:/QualComm/AIStack/QAIRT/2.45.0.260326"
            }
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
